2024-08-20 10:05:36,025 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Current SDK version is 0.17.7
2024-08-20 10:05:36,026 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Configure stats pid to 30620
2024-08-20 10:05:36,026 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Loading settings from C:\Users\30293\.config\wandb\settings
2024-08-20 10:05:36,026 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Loading settings from D:\FG-SSL-main\wandb\settings
2024-08-20 10:05:36,026 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-20 10:05:36,026 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': 'D:\\FG-SSL-main\\main.py', 'program': 'main.py'}
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_init.py:_log_setup():524] Logging user logs to D:\FG-SSL-main\wandb\run-20240820_100536-oj60cqlb\logs\debug.log
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_init.py:_log_setup():525] Logging internal logs to D:\FG-SSL-main\wandb\run-20240820_100536-oj60cqlb\logs\debug-internal.log
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_init.py:init():607] calling init triggers
2024-08-20 10:05:36,027 INFO    MainThread:30620 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {'seed': 0, 'model': 'pmg', 'patches': [32, 16, 8], 'table': None, 'dataset': 'aptos', 'beta': 1, 'cut_prob': -1.1, 'resize': 256, 'centercrop': 224, 'featdim': 512, 'epochs': 1000, 'batchsize': 64, 'lr': 0.01, 'momentum': 0.9, 'weight_decay': 0.0005, 'device': device(type='cpu'), 'num_classes': 5}
2024-08-20 10:05:36,028 INFO    MainThread:30620 [wandb_init.py:init():657] starting backend
2024-08-20 10:05:36,028 INFO    MainThread:30620 [wandb_init.py:init():661] setting up manager
2024-08-20 10:05:36,035 INFO    MainThread:30620 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-08-20 10:05:36,036 INFO    MainThread:30620 [wandb_init.py:init():669] backend started and connected
2024-08-20 10:05:36,045 INFO    MainThread:30620 [wandb_init.py:init():764] updated telemetry
2024-08-20 10:05:36,046 INFO    MainThread:30620 [wandb_init.py:init():797] communicating run to backend with 90.0 second timeout
2024-08-20 10:05:37,287 ERROR   MainThread:30620 [wandb_init.py:init():823] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-20 10:05:37,288 ERROR   MainThread:30620 [wandb_init.py:init():1235] error in wandb.init()
Traceback (most recent call last):
  File "D:\666\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 1225, in init
    return wi.init()
  File "D:\666\envs\pytorch\lib\site-packages\wandb\sdk\wandb_init.py", line 829, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2024-08-20 10:05:40,139 WARNING MsgRouterThr:30620 [router.py:message_loop():77] message_loop has been closed
